### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by JasonPokines** [petervanderdoes/avh-em-permalinks#1]
Using the plugin creates the correct permalink address, but navigating to the page yields a 404 - Page Not Found error. I have gone to Wordpress settings to re-set the permalink structures, but that doesn't seem to initiate any rewrites. I have done this with my .htaccess file blank (original) and with the recommended permalink rewrite code added:

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
```

Example:
Setting the Event slug as "support/classes/%event_name%-%event_monthnum%-%event_day%-%event_year%" yields the permalink "http://beckettconcept.com/wordpress/support/classes/electricity-controls-05-14-2015/" when editing single event page within wordpress, but is unfound when viewing page directly.

This is happening on Wordpress 4.2.1 on a Linux server running Apache v2.2.29, PHP v5.4.36, and MySQL v5.5.42-cll.

**Comment by petervanderdoes** [comment]
Sorry for the looooooooooooong delay.

The permalink that's created adds "wordpress", but the site doesn't seem to have this structure.
I'm not sure why this is added. Do you run WordPress in a subfolder?

**Comment by JasonPokines** [comment]
No worries, we've all been there.

Early on, I did (and still do) have wordpress in a subfolder, but I've since recalibrated it to not show the "/wordpress" in the url. I haven't tried this plugin with that change in place, but I'll try again soon and keep you posted.

**Comment by petervanderdoes** [comment]
Thanks @JasonPokines

**Comment by JasonPokines** [comment]
I've reinstalled the plugin and set the event slug to

> support/classes/%event_name%-%event_monthnum%-%event_day%-%event_year%

which yields a 404 page with the URL "[https://www.beckettconcept.com/support/classes/hands-on-residential-3-08-06-2015](https://www.beckettconcept.com/support/classes/hands-on-residential-3-08-06-2015/)."

**Comment by JasonPokines** [comment]
I've reinstalled the plugin and set the event slug to

> support/classes/%event_name%-%event_monthnum%-%event_day%-%event_year%

which yields a 404 page with the URL "[https://www.beckettconcept.com/support/classes/hands-on-residential-3-08-06-2015](https://www.beckettconcept.com/support/classes/hands-on-residential-3-08-06-2015)."

PS, excuse the close and reopen; I hit the wrong button.

**Comment by petervanderdoes** [comment]
@JasonPokines 

As per commit 9e8d919e32 this problem should be resolved.

**Comment by JasonPokines** [comment]
I'll check again, though I should note that the "-3" in my url was because the base event's name was "hands-on-residential-3" as it was the third class with that name. (Hence why I'm keen to use your plugin!)

**Comment by JasonPokines** [comment]
Well done, good sir!

https://www.beckettconcept.com/support/classes/2015/10/29/electricity-controls-2/

**Comment by petervanderdoes** [comment]
You're welcome.

I will keep working on the plugin, and at one point I might add it to the official WordPress plugin repository,

**Comment by petervanderdoes** [comment]
BTW, I just checked. Because of the way WordPress handles slugs, you will always get a counter if you use the same slug multiple times.

So in you example, if you have the course "hands-on-residential" more than once, the second time you host this course the slug will become "hands-on-residential-2". Not sure if this can be solved.

**Comment by JasonPokines** [comment]
I was just about to come back and comment on that. It's not desirable, and still happens when I make the slugs into prefixes with a slash instead of a dash, e.g. "...2015/08/11/hands-on-residential-2." However, getting the date in the URL without having to hand-type a unique name is the most important part, and you've made that possible for me. Thank you very, very much.

I have a related feature request, which I'll redirect into another "issue" if you prefer. It would be nice to have the month name instead of the number, so that there isn't confusion between knowing which is the day and which is the month.

**Comment by petervanderdoes** [comment]
If you can create a new issue that would be helpful.
