### ISSUE TITLE
Feature request: Add non-numerical month structure tag.

### ISSUE THREAD

**Issue by JasonPokines** [petervanderdoes/avh-em-permalinks#2]
It would be nice to have the month name instead of the number, so that there isn't confusion between knowing which is the day and which is the month if you use "%event_monthnum%" and "%event_day%" in your slug. Otherwise, depending on what country you're from, "postname-08-11" could read as either August 11th or the 8th of November.

**Comment by petervanderdoes** [comment]
Just pushed a version to develop that would accommodate this.

The new tags are:
- %event_monthname_short%
- %event_monthname_long%

**Comment by JasonPokines** [comment]
Nice! Looks to be working for me.
https://www.beckettconcept.com/support/classes/2015/september-22/commercial-burners/

Well done, good sir.
